### ISSUE TITLE
Dive creates dive.log even with logging disabled

### ISSUE THREAD

**Issue by carlosedp** [wagoodman/dive#146]
Dive is creating an empty (0 bytes) `dive.log` file in the current dir even with logging disabled. Here is my `.dive.yaml` file:

```yaml
log:
  enabled: false
  path: ./dive.log
  level: info
filetree:
  # The default directory-collapse state
  collapse-dir: true
```
