### ISSUE TITLE
Can't set `podman` in config file

### ISSUE THREAD

**Issue by abitrolly** [wagoodman/dive#267]
```
✗ dive --config dive.yaml fcc
Using config file: dive.yaml
Image Source: docker://fcc
Fetching image... (this can take a while for large images)
Handler not available locally. Trying to pull 'fcc'...
cannot fetch image
cannot find docker client executable
```
```yaml
✗ cat dive.yaml 
source: podman
container-image: podman

keybinding:
        quit: q
```
