### ISSUE TITLE
Failed to Create Container After Upgrading to 0.13.0

### ISSUE THREAD

**Issue by siddjellali** [wagoodman/dive#576]
## Problem Description
After upgrading to version 0.13.0, container creation fails with the following error:

```
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
```

## Steps to Reproduce

Upgrade to version 0.13.0
Start a container using containerd
Observe the error

## Expected Behavior
The container should be created and start without issues.

## Additional Information
The container runs using an official image from Docker Hub in CI/CD pipelines.

**Comment by DeanAyalon** [comment]
What command are you running? Sorry if I misunderstand, but what does Dive have to do with starting containers?

**Comment by siddjellali** [comment]
I'm using it in the CI pipeline.


```yaml
dive_analysis:
  image:
    name: wagoodman/dive:v0.12
    entrypoint: [""]
  stage: $[[ inputs.stage ]]
  before_script:
    - echo "Installing Skopeo..."
    - apk add skopeo
    - echo "Authenticating to registry..."
    - mkdir ~/.docker/
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > ~/.docker/config.json
  script:
    - echo "Pulling image from SKOPEO and saving locally..."
    - skopeo copy docker://${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} docker-archive:archive.tar
    - echo "Running dive analysis..."
    - dive docker-archive://archive.tar --ci --highestUserWastedPercent disabled --highestWastedBytes 20MB --lowestEfficiency 0.99
  rules:
    - if: $CI_COMMIT_TAG
```
